// 11th grade ("Türkiye Yüzyılı Maarif Modeli") Kaynak Takibi curriculum -- data
// generated by scripts/parse-maarif11-curriculum.mjs from the coach's list in
// supabase/curriculum-source/"11. Sınıf - Taslak Dosyası.txt". Do not
// hand-edit the JSON; re-run the script.
//
// Same shape and conventions as ./maarif9 and ./maarif10 (Course/Unit/Topic;
// deeper headings merged into the topic name with " › "). The JSON keeps the
// list's hierarchy numbers ("1.1. Serbest Düşme › 1.1.1. Serbest Düşen
// Cisimler") because they carry the ordering; withCleanTopicNames strips them
// here so no screen shows them (see ./topic-name).
//
// There is no 11th-grade Genel Deneme data (MAARIF_GRADES[11].examSubjects
// stays empty), only this Kaynak Takibi list.
import type { Course } from "./index";
import kaynakTakibiJson from "./maarif11.json";
import { withCleanTopicNames } from "./topic-name";

export type Maarif11Track = "sayisal" | "ea" | "sozel";

export type Maarif11Topic = { id: string; name: string };
export type Maarif11Unit = { unit: string; topics: Maarif11Topic[] };
export type Maarif11Course = { id: string; name: string; units: Maarif11Unit[] };

export const MAARIF11_COURSES: Maarif11Course[] = withCleanTopicNames(kaynakTakibiJson as Maarif11Course[]);

export const MAARIF11_KAYNAK_COURSES: Course[] = MAARIF11_COURSES;

// Which AYT track(s) each course belongs to -- drives the "11. Sınıf" tab's
// one-click Sayısal / Eşit Ağırlık / Sözel switcher (components/course-tabs.tsx).
// A subject can sit in more than one track, as in the real exam structure.
export const MAARIF11_COURSE_TRACKS: Record<string, Maarif11Track[]> = {
  "maarif11-matematik": ["sayisal", "ea"],
  "maarif11-fizik": ["sayisal"],
  "maarif11-kimya": ["sayisal"],
  "maarif11-biyoloji": ["sayisal"],
  "maarif11-turk-dili-ve-edebiyati": ["sayisal", "ea", "sozel"],
  "maarif11-tarih": ["ea", "sozel"],
  "maarif11-cografya": ["ea", "sozel"],
  "maarif11-felsefe": ["ea", "sozel"],
};

export function tracksForMaarif11Course(courseId: string): Maarif11Track[] {
  return MAARIF11_COURSE_TRACKS[courseId] ?? [];
}

export function isMaarif11CourseId(courseId: string | null | undefined): boolean {
  return !!courseId && courseId.startsWith("maarif11-");
}
