// 10th grade ("Türkiye Yüzyılı Maarif Modeli") curriculum constants -- data
// only, generated by scripts/parse-maarif10-curriculum.mjs from
// supabase/curriculum-source/"10. Sınıf - Taslak Dosyası.xlsx". Do not
// hand-edit the JSON; re-run the script.
//
// NOT wired into lib/curriculum/index.ts, the coach forms or the database:
// importing this file changes nothing in the app.
//
// Same shape and conventions as ./maarif9 (Course/Unit/Topic; deeper sheet
// headings merged into the topic name with " › "; `unit: null` where the sheet
// has no unit level, e.g. İngilizce's themes and the Genel Deneme's
// Coğrafya / Din / Felsefe lists).
import type { Course } from "./index";
import genelDenemeJson from "./maarif10-genel-deneme.json";
import kaynakTakibiJson from "./maarif10.json";

export type Maarif10Topic = { id: string; name: string };
export type Maarif10Unit = { unit: string | null; topics: Maarif10Topic[] };

// "10. Sınıf Kaynak Takibi" -- one course per subject.
export type Maarif10Course = { id: string; name: string; units: Maarif10Unit[] };
export const MAARIF10_COURSES: Maarif10Course[] = kaynakTakibiJson as Maarif10Course[];

// "10. Sınıf Genel Deneme Analizi" -- the sheet's own, separate structure
// (grouped TÜRKÇE / SOSYAL BİLİMLER / MATEMATİK / FEN BİLİMLERİ; no İngilizce).
export type Maarif10GenelDenemeSubject = { id: string; group: string; name: string; units: Maarif10Unit[] };
export const MAARIF10_GENEL_DENEME_SUBJECTS: Maarif10GenelDenemeSubject[] = genelDenemeJson as Maarif10GenelDenemeSubject[];

export function isMaarif10CourseId(courseId: string | null | undefined): boolean {
  return !!courseId && courseId.startsWith("maarif10-");
}

// The same lists as ordinary Course objects (a null unit label becomes "").
export const MAARIF10_KAYNAK_COURSES: Course[] = MAARIF10_COURSES.map((c) => ({
  id: c.id,
  name: c.name,
  units: c.units.map((u) => ({ unit: u.unit ?? "", topics: u.topics })),
}));

export const MAARIF10_GENEL_DENEME_COURSES: Course[] = MAARIF10_GENEL_DENEME_SUBJECTS.map((s) => ({
  id: s.id,
  name: s.name,
  units: s.units.map((u) => ({ unit: u.unit ?? "", topics: u.topics })),
}));
