// 9th grade ("Türkiye Yüzyılı Maarif Modeli") curriculum constants -- data
// only, generated by scripts/parse-maarif9-curriculum.mjs from
// supabase/curriculum-source/"9. Sınıf - Taslak Dosyası.xlsx". Do not
// hand-edit the JSON; re-run the script.
//
// NOT wired into lib/curriculum/index.ts, the coach forms or the database
// yet: importing this file changes nothing in the app.
//
// Shape matches lib/curriculum's Course/Unit/Topic (id + name; Unit.unit is
// the Tema/Ünite label), with two differences worth knowing:
//   - deeper sheet headings are merged into the topic name with " › ",
//     e.g. "1.2. Metin Türleri › Deneme";
//   - Genel Deneme's Türk Dili list has no themes, so its single unit has
//     `unit: null`.
import type { Course } from "./index";
import genelDenemeJson from "./maarif9-genel-deneme.json";
import kaynakTakibiJson from "./maarif9.json";

export type Maarif9Topic = { id: string; name: string };
export type Maarif9Unit = { unit: string | null; topics: Maarif9Topic[] };

// "9. Sınıf Kaynak Takibi" -- one course per subject.
export type Maarif9Course = { id: string; name: string; units: Maarif9Unit[] };
export const MAARIF9_COURSES: Maarif9Course[] = kaynakTakibiJson as Maarif9Course[];

// "9. Sınıf Genel Deneme Analizi" -- the sheet's own, separate structure
// (grouped TÜRKÇE / SOSYAL BİLİMLER / MATEMATİK / FEN BİLİMLERİ; Coğrafya
// units carry one topic each and Din Kültürü is units only, exactly as the
// sheet lists them; no İngilizce).
export type Maarif9GenelDenemeSubject = { id: string; group: string; name: string; units: Maarif9Unit[] };
export const MAARIF9_GENEL_DENEME_SUBJECTS: Maarif9GenelDenemeSubject[] = genelDenemeJson as Maarif9GenelDenemeSubject[];

export function isMaarif9CourseId(courseId: string | null | undefined): boolean {
  return !!courseId && courseId.startsWith("maarif9-");
}

// The Genel Deneme sheet's subjects as ordinary Course objects (a null unit
// label becomes ""), used for the per-topic analysis step of a 9th-grade
// Genel Deneme. Ids are "maarif9-gd-*", distinct from the Kaynak Takibi
// courses above.
export const MAARIF9_GENEL_DENEME_COURSES: Course[] = MAARIF9_GENEL_DENEME_SUBJECTS.map((s) => ({
  id: s.id,
  name: s.name,
  units: s.units.map((u) => ({ unit: u.unit ?? "", topics: u.topics })),
}));

// The Kaynak Takibi courses as ordinary Course objects (every unit there
// carries a Tema/Ünite label; `?? ""` only satisfies the type).
export const MAARIF9_KAYNAK_COURSES: Course[] = MAARIF9_COURSES.map((c) => ({
  id: c.id,
  name: c.name,
  units: c.units.map((u) => ({ unit: u.unit ?? "", topics: u.topics })),
}));
