// One-off admin utility: creates a real, correctly-formatted phone-auth
// account the exact same way approveSignupRequest() does in
// app/admin/actions.ts -- through the Supabase Admin API
// (auth.admin.createUser), never raw SQL. This guarantees:
//   - the password hash is generated by Supabase's own Auth service
//     (GoTrue), so it is verifiable by signInWithPassword() -- a hash
//     built by hand in SQL is not guaranteed to be.
//   - the phone number is normalized by GoTrue itself, so it matches
//     exactly what a real login lookup will search for -- a raw SQL
//     INSERT into auth.users bypasses that normalization and can create
//     a phone value that never matches at login time.
//   - role goes into app_metadata (the only field handle_new_user(), see
//     migration 0062, trusts for role) so public.profiles.role comes out
//     correct immediately -- no follow-up UPDATE ever needed.
//
// This script is for YOU (the project owner) to run locally with your
// own service-role key. It is never called from the deployed app or from
// Claude -- the service-role key never leaves your machine.
//
// IMPORTANT: point it at your REAL hosted Supabase project, not the local
// Docker stack. .env.local is normally set up for `npx supabase start`
// (NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321), which has nothing
// listening unless that local stack is running -- pointing this script at
// it just gets you a generic "fetch failed". Use a separate env file with
// your PRODUCTION values (from Vercel -> Settings -> Environment
// Variables, or Supabase -> Project Settings -> API) instead, e.g.
// .env.production-admin.local (already covered by the .env* line in
// .gitignore, so it can't get committed):
//
//   NEXT_PUBLIC_SUPABASE_URL=https://<your-project-ref>.supabase.co
//   SUPABASE_SERVICE_ROLE_KEY=<your real service role key>
//
// Usage (run from the project root):
//   node --env-file=.env.production-admin.local scripts/create-account.mjs "+905432046683" "AdminPass2026!" admin "Test Admin"
//
// Phone MUST be in +90XXXXXXXXXX format (same as normalizeTurkishPhone()
// in lib/phone.ts produces). Role must be one of: student, parent, coach, admin.

import { createClient } from "@supabase/supabase-js";

const [, , phone, password, role, ...nameParts] = process.argv;
const fullName = nameParts.join(" ") || null;

const VALID_ROLES = new Set(["student", "parent", "coach", "admin"]);

if (!phone || !password || !role) {
  console.error("Usage: node --env-file=<your-env-file> scripts/create-account.mjs <phone> <password> <role> [full name]");
  console.error("Example: node --env-file=.env.production-admin.local scripts/create-account.mjs \"+905432046683\" \"AdminPass2026!\" admin \"Test Admin\"");
  process.exit(1);
}
if (!/^\+90\d{10}$/.test(phone)) {
  console.error(`Phone "${phone}" doesn't look like +90XXXXXXXXXX (must be +90 followed by exactly 10 digits). Refusing to proceed.`);
  process.exit(1);
}
if (!VALID_ROLES.has(role)) {
  console.error(`Role "${role}" is not one of: ${[...VALID_ROLES].join(", ")}`);
  process.exit(1);
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !serviceKey) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.");
  console.error("Make sure you ran this with: node --env-file=<your-env-file> scripts/create-account.mjs ...");
  process.exit(1);
}

// Catch the #1 cause of a bare "fetch failed": pointed at the local
// Docker stack (127.0.0.1 / localhost) instead of the real hosted
// project, with nothing listening there.
if (/^https?:\/\/(127\.0\.0\.1|localhost|\[::1\])/i.test(url)) {
  console.error(`NEXT_PUBLIC_SUPABASE_URL is "${url}" -- that's the LOCAL Supabase Docker address, not your hosted project.`);
  console.error("This only works if you've run `npx supabase start` and have that local stack up.");
  console.error("To create an account in your REAL production project instead, point --env-file at a file containing");
  console.error("your production NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY (from Vercel -> Settings ->");
  console.error("Environment Variables, or Supabase -> Project Settings -> API) -- see the comment at the top of this file.");
  process.exit(1);
}

console.log(`Using Supabase project: ${url}`);

const supabase = createClient(url, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } });

let result;
try {
  result = await supabase.auth.admin.createUser({
    phone,
    password,
    phone_confirm: true,
    app_metadata: { role },
    user_metadata: fullName ? { full_name: fullName } : undefined,
  });
} catch (e) {
  console.error("Request itself threw (not a Supabase API error):", e);
  if (e?.cause) console.error("Underlying cause:", e.cause);
  process.exit(1);
}

const { data, error } = result;
if (error) {
  console.error("Failed:", error.message);
  if (error.cause) console.error("Underlying cause:", error.cause);
  if (error.message === "fetch failed") {
    console.error("This usually means NEXT_PUBLIC_SUPABASE_URL is unreachable from this machine right now --");
    console.error("double-check it's your real project URL (https://<ref>.supabase.co) and that you have network access to it.");
  }
  process.exit(1);
}

console.log(`Created ${role} account: ${phone} (user id: ${data.user.id})`);
console.log("public.profiles.role should already be correct via the handle_new_user() trigger -- verify in Table Editor if you want to double check.");
